### PR TITLE
Add option to not launch the browser automatically via LocalWebserver…

### PR DESCRIPTION
**Pull request by benhoman**
…Auth.

This PR adds the functionality to allow a user to tell GoogleAuth.LocalWebserverAuth not to launch the default browser automatically. It defaults to the current functionality.

### CODE REVIEW

**Comment by shcheklein** [comment]
@benhoman please check the `pre-commit / pre-commit (pull_request)` CI check above. I think we need to fix this PRs style (indents, etc). Consider running `pre-commit` locally.

Tests are failing for unrelated reasons - @efiop @casperdcl @skshetry @isidentical how do you/do you run test in forks? Is there a mechanism (let's say I approve them here) to make it secure these days?

**Comment by benhoman** [comment]
@shcheklein I installed/ran pre-commit locally and it formatted the auth.py file. Looks like there was a line length issue. Thanks for the feedback, pre-commit is a new tool for me.

**Comment by casperdcl** [comment]
@shcheklein we could merge into a branch on this repo first. Just created a `pr-139` branch...

**Review by casperdcl — APPROVED** [review]

**Comment by casperdcl** [comment]
nvm github already auto-closed :)

local branch: #140

**Comment by shcheklein** [comment]
@benhoman we've published the new release. It'll be available soon on PyPi and conda.

**Pull request merged**
