### PR TITLE
Add .GetRevisions() option

### PR DESCRIPTION
**Pull request by rasa**

### CODE REVIEW

**Comment by rasa** [comment]
The code works, but I'm unable to figure out how to install the `extras_require` packages to get the tests to run.

**Comment by shcheklein** [comment]
@rasa thanks! pre-commit hook fails, please check the output, run linters locally to fix it. After that we can run the tests on CI.

> The code works, but I'm unable to figure out how to install the extras_require packages to get the tests to run.

Has to be something like (in a virtualenv):

```
pip install -e ".[tests]"
```

**Comment by rasa** [comment]
> pip install -e ".[tests]"

Thanks! I tried
`pip install -e ".[extras]"`
before, but it didn't work. 
I just ran
`pip install -e ".[tests]"`
but then I needed to run
`pip install -e ".[fsspec]"`
as `fsspec` and `appdirs` needed to be installed.

If I had foresight, I would have checked [here](https://github.com/iterative/PyDrive2/blob/30c0f487c0666c0d1944ef774107359f39adc2fa/.github/workflows/test.yml#L40C12-L40C55) where I would have found `python -m pip install -e '.[fsspec, tests]'`

When I run the tests, the first Google Signin works, but the next two just spin forever at
```text
pydrive2/test/test_apiattr.py F                                                                                                                                                      [  2%]
pydrive2/test/test_drive.py E                                                                                                                                                        [  4%]
pydrive2/test/test_file.py EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEsEEEE                                                                                                                  [ 58%]
pydrive2/test/test_filelist.py EEEE                                                                                                                                                  [ 63%]
pydrive2/test/test_fs.py .FFEEEEEEEEEEEE                                                                                                                                             [ 83%]
pydrive2/test/test_oauth.py .F
```

**Comment by shcheklein** [comment]
@rasa looks like also Python 3.8 / 3.9 tests fail. Please check the logs above.

**Comment by rasa** [comment]
> @rasa looks like also Python 3.8 / 3.9 tests fail. Please check the logs above.

The [logs](https://github.com/iterative/PyDrive2/actions/runs/5767837480/job/15645353833#step:5:14) show the same error that occurred on July 10 in [these logs](https://github.com/iterative/PyDrive2/actions/runs/5514637146/job/14930002327#step:5:14) so I don't think the issue is with my PR. The July 5 [run](https://github.com/iterative/PyDrive2/actions/runs/5463979454/job/14792404645#step:5:14) was the last to succeed.

**Comment by shcheklein** [comment]
Yes, you are right, most likely PyInstaller got updated actually. We'll check that.

**Pull request merged**
