### PR TITLE
docs: add docs for creating a GoogleDriveFile by ID

### PR DESCRIPTION
**Pull request by jsquyres**
Many thanks for PyDrive2!

I had a use case where I had obtained a Google File ID by another mechanism, but wanted to use it with the PyDrive2 API.  This didn't appear to be documented anywhere, but it does appear to be supported.  Hence, I wrote a short example showing how to do it.

Hopefully this is useful to you!

### CODE REVIEW

**Comment by shcheklein** [comment]
@jsquyres thanks! it's an excellent example. Let's make it part of the existing section - https://docs.iterative.ai/PyDrive2/filemanagement/ ? wdyt?

**Comment by shcheklein** [comment]
Something like this https://docs.iterative.ai/PyDrive2/filemanagement/#download-file-metadata-from-file-id

**Comment by jsquyres** [comment]
Wow, those `file['id']` examples were already there and I somehow totally missed them... 😲 

Is my example even relevant given that https://docs.iterative.ai/PyDrive2/filemanagement/#download-file-metadata-from-file-id both https://docs.iterative.ai/PyDrive2/filemanagement/#download-file-content both mention `drive.Createfile({ 'id': fileX['id'] })`?

E.g., are you suggesting that I take the section in this PR and put it at the end of filemanagement, after the "Download file content" section?

**Comment by shcheklein** [comment]
Yep, I also didn't check those sections. It is less relevant then. I'm fine to close this PR then. :)

**Pull request closed without merging**
