### PR TITLE
Fix dependencies

### PR DESCRIPTION
**Pull request by shcheklein**
First step to fix https://github.com/iterative/dvc/issues/3215 . More context is here - https://stackoverflow.com/a/59850170/298182

Step needed to fix `gdrive` dependencies in the DVC core repo, specifically these lines https://github.com/iterative/dvc/blob/master/setup.py#L87-L89

@efiop was you able to run tests/CI/stylers for this repo?

- [ ] Will need to update `conda` deps and release new version to pip/conda.

### CODE REVIEW

**Comment by efiop** [comment]
> @efiop was you able to run tests/CI/stylers for this repo?

Not yet 🙁 https://github.com/iterative/PyDrive2/issues/3

**Comment by efiop** [comment]
Released 1.4.1, will adjust conda soon too.

**Comment by shcheklein** [comment]
@efiop thanks! I'll create a PR to DVC core tomorrow.

**Comment by efiop** [comment]
@shcheklein I've adjusted already.

**Comment by shcheklein** [comment]
thanks!

**Comment by efiop** [comment]
For the record: fixed conda https://github.com/conda-forge/pydrive2-feedstock/pull/1

**Pull request merged**
