### PR TITLE
Fix links in documentation

### PR DESCRIPTION
**Pull request by tmotyl**

### CODE REVIEW

**Comment by shcheklein** [comment]
thanks @tmotyl for taking care of this.

I think all link should start with `./PyDrive2/..` ... e.g. 

https://docs.iterative.ai/PyDrive2/pydrive2/#pydrive2.apiattr.ApiResource
https://docs.iterative.ai/PyDrive2/quickstart/#creating-and-updating-files

`./pydrive2/#pydrive2.apiattr.ApiResource` alone won't be enough.

**Review by shcheklein — CHANGES_REQUESTED** [review]
Fix links prefix

**Comment by tmotyl** [comment]
Why do you think so? My previous patch fixed links.

**Comment by tmotyl** [comment]
Please notice that i hanged links to absolute path(no dot at beginning).

**Comment by shcheklein** [comment]
I did this commit after we merged to fix this - https://github.com/iterative/PyDrive2/commit/1d0847ac0e6f5f70581208112d4c2a7405e05bed

(I'm not sure about `.`  - I hope it's pretty much the same w or w/o it to be honest)

**Comment by tmotyl** [comment]
thanks for the explanation, here you go :)

**Review by shcheklein — APPROVED** [review]

**Comment by shcheklein** [comment]
Thanks @tmotyl !

**Pull request merged**
