### PR TITLE
docs theme

### PR DESCRIPTION
**Pull request by casperdcl**
- [x] use [Furo theme](https://pradyunsg.me/furo/) (left & right nav bars, light & dark mode toggle)
- [x] update URLs & metadata
- [x] add Index to ToC
- [x] add proper GitHub pages support
  + add `docs/README.md` instructions
  + remove deployed `docs/build` in favour of `gh-pages` branch
  + native config (`.nojekyll`, `CNAME`, etc.)
- [x] rebuild site
  + compare: [old (current)](https://iterative.github.io/PyDrive2/docs/build/html/index.html) vs [new (preview)](https://cdcl.ml/test)
- [x] update site location - https://iterative.github.io/PyDrive2/docs/build/html/index.html is horrible and really should be one of:

|   | URL convention | needs DNS config | future repos need DNS config |
|---|-----|---|---|
| 1 :+1: | https://docs.iterative.ai/PyDrive2/ <-- current winner | :white_check_mark: (done :grin:) | :x: :grin: |
| 2 :smile: | https://pydrive2.iterative.ai/ | :white_check_mark: :slightly_frowning_face: | :ballot_box_with_check: :disappointed: |
| 3 :tada: | https://pydrive2.iterative.ai/docs/ | :white_check_mark: :slightly_frowning_face: | :ballot_box_with_check: :disappointed: |
| 4 :heart: | https://iterative.github.io/PyDrive2/ | :x: :slightly_smiling_face: | :x: :grin: |
| 5 :rocket: | https://iterative.github.io/PyDrive2/docs/ | :x: :slightly_smiling_face: | :x: :grin: |

vote using :+1:/:smile:/:tada:/:heart:/:rocket:

### CODE REVIEW

**Comment by isidentical** [comment]
+1 on the (1) as well!

**Comment by skshetry** [comment]
I prefer (2) mostly, `cml.iterative.ai`, `pydrive2.iterative.ai`, `dvc.iterative.ai`, `studio.iterative.ai`, `live.iterative.ai` namespacing. It's easier to type, and even easier on autocompletion. 

1) might be better for search engine ranking.

**Comment by shcheklein** [comment]
I think we need to do 2. If we do 1, we need to introduce some prefix like oss.iterative.ai/PyDrive2. iterative.ai is a corporate landing page, urls like iterative.ai/PyDrive2 look a bit strange there to be honest.

Can we move the docs into the branch also, as we discussed with you?

Is there preview available for this?

**Comment by casperdcl** [comment]
> I think we need to do 2. If we do 1, we need to introduce some prefix like oss.iterative.ai/PyDrive2. iterative.ai is a corporate landing page, urls like iterative.ai/PyDrive2 look a bit strange there to be honest.

Option (1) is `docs.iterative.ai/PyDrive2`, not `iterative.ai/PyDrive2`!

> Can we move the docs into the branch also, as we discussed with you?

Yes, just added to this PR.

> Is there preview available for this?

Coming soon.

**Comment by casperdcl** [comment]
rebased and non-squash-merged to keep a clean debuggable history in case of errors.

**Pull request merged**
