### PR TITLE
Support JSON based service auth

### PR DESCRIPTION
**Pull request by isidentical**

### CODE REVIEW

**Review by shcheklein — APPROVED** [review]

**Comment by shcheklein** [comment]
@isidentical @efiop do we need to release the new version asap?

**Comment by isidentical** [comment]
> @isidentical @efiop do we need to release the new version asap?

It would be great if you are free. (So that I can fix the fixture on the dvc)

**Comment by efiop** [comment]
@isidentical Created 1.7.3, should be ready soon https://github.com/iterative/PyDrive2/releases/tag/1.7.3.

**Comment by isidentical** [comment]
@efiop would you update the GDRIVE_ environment secret on the DVC as well (just like this one)?

**Comment by efiop** [comment]
@isidentical Updated GDRIVE_ env secret in dvc repo.

**Comment by isidentical** [comment]
Thanks very much!

**Pull request merged**
