### PR TITLE
mention saving and loading credentials

### PR DESCRIPTION
**Pull request by NikolasE**
In the current description, the authentication process is repeated every time.

### CODE REVIEW

**Review by shcheklein — COMMENTED** [review]
@NikolasE this should not be needed to do auth, unless I'm missing something.

**Comment by shcheklein** [comment]
> In the current description, the authentication process is repeated every time.

@NikolasE could you clarify please?

**Comment by NikolasE** [comment]
This was my experience:
- started first snippet, clicked through the process, docu said "click Accept and you are done with authentication."
- moved to next snippet, added the next lines, started the script, again forced to do the whole process instead of having fun with the gdrive files. 
- looked through code to find how credentials can be stored so that I'm really done with auth and can start wo work. 

IMHO a quickstart should move quite quickly to something that works like to the final process and I assume that most other users would also start to search for the save/load functions after clicking through the auth process twice.

**Comment by shcheklein** [comment]
@NikolasE I'm not sure still if I understand the issue correctly.

> I assume that most other users would also start to search for the save/load functions after clicking through the auth process twice

could you clarify on this please? I assume that users don't need to do this, especially using direct helpers in code. The path for this file should be fine by default + it can be set by the settings.yaml or by the settings passed into auth init.

**Comment by shcheklein** [comment]
Closing as stale. @NikolasE feel free to follow up on this.

**Pull request closed without merging**
