### PR TITLE
Add function to load credentials from server

### PR DESCRIPTION
**Pull request by shinz4u**
Allow passing a dictionary filled with credentials to `LoadCredentials()` method and `LoadCredentialsFromServer()` implemented which sets the credentials.

```
  credentials_dict = {
            "access_token": None,
            "client_id": None,
            "client_secret": None,
            "refresh_token": None,
            "token_expiry": None,
            "token_uri": "https://accounts.google.com/o/oauth2/token",
            "user_agent": None,
            "revoke_uri": "https://oauth2.googleapis.com/revoke",
            "id_token": None,
            "id_token_jwt": None,
            "token_response": {
                "access_token": None,
                "expires_in": 3599,
                "refresh_token": None,
                "scope": "https://www.googleapis.com/auth/drive",
                "token_type": "Bearer"
            },
            "scopes": ["https://www.googleapis.com/auth/drive"],
            "token_info_uri": "https://oauth2.googleapis.com/tokeninfo",
            "invalid": False,
            "_class": "OAuth2Credentials",
            "_module": "oauth2client.client"
        }
```

**Couple of questions**

1. This method worked for me for my project, but I am not sure about the security implications. Do advice whether this will suffice? 
2. I am handling refreshing on the server side by calling `gauth.Refresh()` and would like to store the new refresh tokens. How can I get the refreshed tokens back?

### CODE REVIEW

**Comment by shcheklein** [comment]
@shinz4u hi, thanks for the PR. A few questions that would help me to review:

Could you please show the server code that you use now to store/pass credentials?

> This method worked for me for my project, but I am not sure about the security implications. Do advice whether this will suffice?

it depends on where do you store these credentials. If it's properly encrypted database then it should be fine to my mind.

> I am handling refreshing on the server side by calling gauth.Refresh() and would like to store the new refresh tokens. How can I get the refreshed tokens back?

hmm .. my feeling is that `gauth.Refresh() ` is not needed to be honest. PyDrive should be handling refresh automatically if everything is set correctly. Could you share the PyDrive config?

**Comment by shinz4u** [comment]
@shcheklein Here is the server side code,

Main method to notice is `upload_file()` which creates a credentials_dict to pass to pydrive and also calls `_store_credentials` so that it can store the refresh tokens and other tokens to the DB.

        from flask import request
        import json as jsonlib
        import traceback
        from sqlalchemy.exc import IntegrityError
        import os
        
        from pydrive2.auth import GoogleAuth
        from pydrive2.drive import GoogleDrive
        
        from . import db
        from app.exceptions import ValidationError, UploadError
        from app.pydrive_settings_generator import PyDriveSettingsGenerator
        from app.recommendation_generator import RecommendationGenerator
        from app.models.user import User
        from app.models.storage import Storage
        
        class GoogleStorage(object):
            def __init__(self, folder_name="__my_app__"):
                self.my_app_folder_name = folder_name
                self.py_drive_settings = PyDriveSettingsGenerator()
        
            def get_auth_url(self, user_id):
                gauth = GoogleAuth(settings_file=self.py_drive_settings.get_settings_file())
                authorization_url = gauth.GetAuthUrl(state=user_id)
                return authorization_url
        
            def callback(self, user_id, code):
                """ Gets the callback from Google with the Auth code and creates credentials and stores them in the DB.
        
                Args:
                    user_id ([int]): user id of the user
                    code ([string]): Google returned oauth code
        
                Returns:
                    [type]: [description]
                """
                gauth = GoogleAuth(settings_file=self.py_drive_settings.get_settings_file())
                gauth.Auth(code)
        
                credential_dict = self._credentials_to_dict(gauth.credentials)
        
                response = self._store_credentials(credential_dict, user_id)
                return response
        
            def upload_file(self, user_id, r_files, r_form):
                """
                Gets credentials fron DB, Uploads the file to Google Drive and also stores new credentials to DB if refresh token expired.
        
                Raises:
                    UploadError: If upload did not complete.
        
                Returns:
                    JSON:
                        Response which indicates whether success or failure with the url and titles
                        Example response:
        
                            {
                                "success": true,
                                "title": "182297.pdf",
                                "url": "https://drive.google.com/file/d/1ObEJz_5DsHkviijDQ8zN49SdTopzaczX"
                                "recommended_tags":["tag1", "tag2", "tag3"],
                                "recommended_title": null
        
                            }
                """
        
                credentials_dict = {
                    "access_token": None,
                    "client_id": os.environ.get("CLIENT_ID"),
                    "client_secret": os.environ.get("CLIENT_SECRET"),
                    "refresh_token": None,
                    "token_expiry": None,
                    "token_uri": "https://accounts.google.com/o/oauth2/token",
                    "user_agent": None,
                    "revoke_uri": "https://oauth2.googleapis.com/revoke",
                    "id_token": None,
                    "id_token_jwt": None,
                    "token_response": {
                        "access_token": None,
                        "expires_in": 3599,
                        "refresh_token": None,
                        "scope": "https://www.googleapis.com/auth/drive",
                        "token_type": "Bearer"
                    },
                    "scopes": ["https://www.googleapis.com/auth/drive"],
                    "token_info_uri": "https://oauth2.googleapis.com/tokeninfo",
                    "invalid": False,
                    "_class": "OAuth2Credentials",
                    "_module": "oauth2client.client"
                }
        
                gauth = GoogleAuth(settings_file=self.py_drive_settings.get_settings_file())
        
                user_credentials = self._get_credentials_from_db(user=user_id)
        
                credentials_dict["access_token"] = user_credentials.access_token
                credentials_dict["refresh_token"] = user_credentials.refresh_token
                credentials_dict["token_expiry"] = str(user_credentials.token_expiry)
        
                credentials_dict["token_response"]["access_token"] = user_credentials.access_token
                credentials_dict["token_response"]["refresh_token"] = user_credentials.refresh_token
        
                credentials_json = jsonlib.dumps(credentials_dict)
        
        
                gauth.LoadCredentials(credentials_json = credentials_json)
        
                if gauth.access_token_expired:
                    print("access_token expired so refreshing", flush=True)
                    gauth.Refresh()
                    self._store_credentials(self._credentials_to_dict(gauth.credentials), user_id)
        
                gdrive = GoogleDrive(gauth)
        
                try:
                    # Try to upload the file
                    file_to_upload = r_files['file']
                    if 'filename' not in r_form:
                        filename = file_to_upload.filename
                    else:
                        ext = file_to_upload.filename.split('.').pop()
                        filename = f'{r_form["filename"]}.{ext}'
        
                    if self._my_app_folder_exists(gdrive):
                        my_app_folder = self._get_my_app_folder(gdrive)
                    else:
                        my_app_folder = self._create_folder(self.my_app_folder_name, gdrive)
        
                    recommendations_generator = RecommendationGenerator()
                    recommended_tags = recommendations_generator.get_tags(file_to_upload, doc_type='file')
                    recommended_text = recommendations_generator.get_title(file_to_upload, doc_type='file')
        
                    url, title = self._upload_file(file_to_upload, filename, my_app_folder, gdrive)
                    response = {
                                "url": url,
                                "filename": title,
                                "recommended_tags": recommended_tags,
                                "recommended_text": recommended_text if recommended_text else title
                                }
        
                    return response
                except:
                    print(traceback.print_exc(), flush=True)
                    raise UploadError("Error: Could not upload file")
        
            def _credentials_to_dict(self, credentials):
                """
                Converts the Google Auth Credentials object to a dictionary
        
                Args:
                    credentials ([type]): Google Auth Credentials object (GoogleAuth.credentials)
        
                Returns:
                    [dict]: credentials dictionary
                """
                new_credentials = {'access_token': credentials.access_token,
                        'client_id': credentials.client_id,
                        'client_secret': credentials.client_secret,
                        'scopes': credentials.scopes,
                        'refresh_token': credentials.refresh_token,
                        'token_uri': credentials.token_uri,
                        'token_expiry': credentials.token_expiry,
                        'revoke_uri': credentials.revoke_uri
                        }
        
                return new_credentials
        
            def _store_credentials(self, credentials, user_id):
                """
                Store credentials to the DB
        
                Args:
                    credentials ([dict]): Google credentials of the user
                    user_id ([type]): [description]
        
                Raises:
                    ValidationError: [description]
        
                Returns:
                    [type]: [description]
                """
                try:
                    response = {}
                    user = User.query.filter(User.id == user_id).first()
        
                    types = [storage.storage_type for storage in user.storages]
                    print(types, flush=True)
                    if 'google' not in types:
                        storage = Storage(
                            user_id = user_id,
                            storage_type = 'google',
                            access_token = credentials["access_token"],
                            refresh_token = credentials["refresh_token"],
                            token_expiry = credentials["token_expiry"],
                        )
        
                        if not user.storages:
                            storage.preferred = True
        
                        user.storages.append(storage)
                        response = {
                                "new_google_user" : "True",
                                "success": "True",
                        }
                    else:
                        storage = [s for s in user.storages if s.storage_type == 'google'][0]
                        # Update Credentials
                        storage.update_data({'access_token': credentials["access_token"],
                                            'refresh_token': credentials["refresh_token"],
                                            'token_expiry': credentials["token_expiry"]
                        })
                        response = {
                            "new_google_user" : "False",
                            "success": "True",
                        }
        
                    db.session.commit()
                    return response
                except IntegrityError as e:
                    db.session.rollback()
                    print(e._message(), flush=True)
                    raise ValidationError("Error: Cannot add credentials to DB!")
        
            def _get_credentials_from_db(self, user):
                try:
                    google_record = Storage.query.filter(Storage.user_id == user, Storage.storage_type == 'google').first()
                    return google_record
                except:
                    print(traceback.print_exc(), flush=True)
                    raise ValidationError("Error: Could not fetch user credentials")
        
            .
            .
            .
            .
            .
            .
        
        
            def _upload_file(self, file_to_upload, filename, parent_folder_id, gdrive):
                """ Converts the given file to a filestream and uploads it through pyDrive2.
        
                Args:
                    file_to_upload (werkzeug.datastructures.FileStorage]): file
                    file_name ([str]): [description]
                    parent_folder_id ([str]): parent folder to which file is uploaded i.e __my_app
                    gdrive ([GoogleDrive Object]): GoogleDrive object of pyDrive2
        
                Returns:
                    [string, string]: url of the resource, filename of the new file
                """
                new_file = gdrive.CreateFile({'title': filename ,"parents": [{"kind": "drive#fileLink", "id": parent_folder_id}]})  # Create GoogleDriveFile instance.
                content = file_to_upload.read()
                new_file.SetContentBytes(content, filename)
                try:
                    new_file.Upload()
                    url = f"https://drive.google.com/file/d/{new_file['id']}"
                    if new_file.uploaded:
                        return url, new_file['title']
                except:
                    raise

**Comment by shinz4u** [comment]
@shcheklein Regarding the refresh tokens. If I don't need to use `gauth.Refresh()`. Then how will I be able to store the refreshed tokens. wIll I be able to know from pydrive that the tokens were refreshed? I will need to store these new tokens to the db too.

**Comment by shinz4u** [comment]
@shcheklein Here is the server side code,

Main method to notice is `upload_file()` which creates a credentials_dict to pass to pydrive and also calls `_store_credentials()` so that it can store the refresh tokens and other tokens to the DB.

        from flask import request
        import json as jsonlib
        import traceback
        from sqlalchemy.exc import IntegrityError
        import os
        
        from pydrive2.auth import GoogleAuth
        from pydrive2.drive import GoogleDrive
        
        from . import db
        from app.exceptions import ValidationError, UploadError
        from app.pydrive_settings_generator import PyDriveSettingsGenerator
        from app.recommendation_generator import RecommendationGenerator
        from app.models.user import User
        from app.models.storage import Storage
        
        class GoogleStorage(object):
            def __init__(self, folder_name="__my_app__"):
                self.my_app_folder_name = folder_name
                self.py_drive_settings = PyDriveSettingsGenerator()
        
            def get_auth_url(self, user_id):
                gauth = GoogleAuth(settings_file=self.py_drive_settings.get_settings_file())
                authorization_url = gauth.GetAuthUrl(state=user_id)
                return authorization_url
        
            def callback(self, user_id, code):
                """ Gets the callback from Google with the Auth code and creates credentials and stores them in the DB.
        
                Args:
                    user_id ([int]): user id of the user
                    code ([string]): Google returned oauth code
        
                Returns:
                    [type]: [description]
                """
                gauth = GoogleAuth(settings_file=self.py_drive_settings.get_settings_file())
                gauth.Auth(code)
        
                credential_dict = self._credentials_to_dict(gauth.credentials)
        
                response = self._store_credentials(credential_dict, user_id)
                return response
        
            def upload_file(self, user_id, r_files, r_form):
                """
                Gets credentials fron DB, Uploads the file to Google Drive and also stores new credentials to DB if refresh token expired.
        
                Raises:
                    UploadError: If upload did not complete.
        
                Returns:
                    JSON:
                        Response which indicates whether success or failure with the url and titles
                        Example response:
        
                            {
                                "success": true,
                                "title": "182297.pdf",
                                "url": "https://drive.google.com/file/d/1ObEJz_5DsHkviijDQ8zN49SdTopzaczX"
                                "recommended_tags":["tag1", "tag2", "tag3"],
                                "recommended_title": null
        
                            }
                """
        
                credentials_dict = {
                    "access_token": None,
                    "client_id": os.environ.get("CLIENT_ID"),
                    "client_secret": os.environ.get("CLIENT_SECRET"),
                    "refresh_token": None,
                    "token_expiry": None,
                    "token_uri": "https://accounts.google.com/o/oauth2/token",
                    "user_agent": None,
                    "revoke_uri": "https://oauth2.googleapis.com/revoke",
                    "id_token": None,
                    "id_token_jwt": None,
                    "token_response": {
                        "access_token": None,
                        "expires_in": 3599,
                        "refresh_token": None,
                        "scope": "https://www.googleapis.com/auth/drive",
                        "token_type": "Bearer"
                    },
                    "scopes": ["https://www.googleapis.com/auth/drive"],
                    "token_info_uri": "https://oauth2.googleapis.com/tokeninfo",
                    "invalid": False,
                    "_class": "OAuth2Credentials",
                    "_module": "oauth2client.client"
                }
        
                gauth = GoogleAuth(settings_file=self.py_drive_settings.get_settings_file())
        
                user_credentials = self._get_credentials_from_db(user=user_id)
        
                credentials_dict["access_token"] = user_credentials.access_token
                credentials_dict["refresh_token"] = user_credentials.refresh_token
                credentials_dict["token_expiry"] = str(user_credentials.token_expiry)
        
                credentials_dict["token_response"]["access_token"] = user_credentials.access_token
                credentials_dict["token_response"]["refresh_token"] = user_credentials.refresh_token
        
                credentials_json = jsonlib.dumps(credentials_dict)
        
        
                gauth.LoadCredentials(credentials_json = credentials_json)
        
                if gauth.access_token_expired:
                    print("access_token expired so refreshing", flush=True)
                    gauth.Refresh()
                    self._store_credentials(self._credentials_to_dict(gauth.credentials), user_id)
        
                gdrive = GoogleDrive(gauth)
        
                try:
                    # Try to upload the file
                    .
                    .
                    .
                    .
                except:
                    print(traceback.print_exc(), flush=True)
                    raise UploadError("Error: Could not upload file")
        
            def _credentials_to_dict(self, credentials):
                """
                Converts the Google Auth Credentials object to a dictionary
        
                Args:
                    credentials ([type]): Google Auth Credentials object (GoogleAuth.credentials)
        
                Returns:
                    [dict]: credentials dictionary
                """
                new_credentials = {'access_token': credentials.access_token,
                        'client_id': credentials.client_id,
                        'client_secret': credentials.client_secret,
                        'scopes': credentials.scopes,
                        'refresh_token': credentials.refresh_token,
                        'token_uri': credentials.token_uri,
                        'token_expiry': credentials.token_expiry,
                        'revoke_uri': credentials.revoke_uri
                        }
        
                return new_credentials
        
            def _store_credentials(self, credentials, user_id):
                """
                Store credentials to the DB
        
                Args:
                    credentials ([dict]): Google credentials of the user
                    user_id ([type]): [description]
        
                Raises:
                    ValidationError: [description]
        
                Returns:
                    [type]: [description]
                """
                try:
                    response = {}
                    user = User.query.filter(User.id == user_id).first()
        
                    types = [storage.storage_type for storage in user.storages]
                    print(types, flush=True)
                    if 'google' not in types:
                        storage = Storage(
                            user_id = user_id,
                            storage_type = 'google',
                            access_token = credentials["access_token"],
                            refresh_token = credentials["refresh_token"],
                            token_expiry = credentials["token_expiry"],
                        )
        
                        if not user.storages:
                            storage.preferred = True
        
                        user.storages.append(storage)
                        response = {
                                "new_google_user" : "True",
                                "success": "True",
                        }
                    else:
                        storage = [s for s in user.storages if s.storage_type == 'google'][0]
                        # Update Credentials
                        storage.update_data({'access_token': credentials["access_token"],
                                            'refresh_token': credentials["refresh_token"],
                                            'token_expiry': credentials["token_expiry"]
                        })
                        response = {
                            "new_google_user" : "False",
                            "success": "True",
                        }
        
                    db.session.commit()
                    return response
                except IntegrityError as e:
                    db.session.rollback()
                    print(e._message(), flush=True)
                    raise ValidationError("Error: Cannot add credentials to DB!")
        
            def _get_credentials_from_db(self, user):
                try:
                    google_record = Storage.query.filter(Storage.user_id == user, Storage.storage_type == 'google').first()
                    return google_record
                except:
                    print(traceback.print_exc(), flush=True)
                    raise ValidationError("Error: Could not fetch user credentials")
        
            .
            .
            .
            .
            .
            .

**Comment by shcheklein** [comment]
Sorry for the delay here @shinz4u .

Unfortunately, I think it should be done in way that things like this:

```python
        gauth.LoadCredentials(credentials_json = credentials_json)

        if gauth.access_token_expired:
            print("access_token expired so refreshing", flush=True)
            gauth.Refresh()
            self._store_credentials(self._credentials_to_dict(gauth.credentials), user_id)
```

are handled inside the driver. User don't have to deal with this (compare it with the regular file-based workflow in which you would not call `LoadCredentials`, neither you would refresh the tocken.

I'm not sure about the implementation from the top of my head, but I think is should be something like:

```python
def load_credentials()
  // load from db
  return <json dict>

def save_credentials(json_dict)
  // save to db
  return

GoogleAuth(
  settings_file=self.py_drive_settings.get_settings_file()
  load_credentials_callback=load_credentials,
  save_credentials_callback=save_credentials
)
```

And we can introduce an alternative credentials backend "callback" or something.

Maybe there are some better alternatives to this, but it should be handled within the GoogleAuth. To be honest I'm not even sure why did they initially make Load public.

**Pull request closed without merging**
